sudo: required
services:
  - docker

before_install:
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -r CI=true stephengrider/docker-react npm run test -- --coverage